#!/bin/bash
# mgba-midisync installer for Knulli / Batocera.
#
# Leaves the stock mGBA core alone. Instead it installs a second core and adds
# two entries to Ports that start FMS / LSDj with it:
#   /userdata/cores/mgba_midisync_libretro.so
#   /userdata/roms/ports/FMS (MIDI Sync).sh
#   /userdata/roms/ports/LSDj (MIDI Sync).sh
#
# Usage (from the unpacked release folder, over SSH):
#   bash install.sh                      # finds FMS / LSDj ROMs by name
#   bash install.sh --fms /userdata/roms/gba/FMS.gba --lsdj /userdata/roms/gb/lsdj.gb
set -e

HERE="$(cd "$(dirname "$0")" && pwd)"
CORE_SRC="$HERE/mgba_midisync_libretro.so"
CORE="/userdata/cores/mgba_midisync_libretro.so"
PORTS="/userdata/roms/ports"
MARK="# Generated by mgba-midisync install.sh"
OLD_BIND="/usr/lib/libretro/mgba_libretro.so"

FMS_ROM=""
LSDJ_ROM=""
while [ $# -gt 0 ]; do
	case "$1" in
		--fms) FMS_ROM="$2"; shift 2 ;;
		--lsdj) LSDJ_ROM="$2"; shift 2 ;;
		-h|--help) sed -n '2,15p' "$0"; exit 0 ;;
		*) echo "unknown option: $1"; exit 1 ;;
	esac
done

if [ ! -f "$CORE_SRC" ]; then
	echo "mgba_midisync_libretro.so not found next to install.sh"
	exit 1
fi

find_rom() { # dir... pattern
	local pattern="$1"; shift
	local d
	for d in "$@"; do
		[ -d "$d" ] || continue
		find "$d" -maxdepth 2 -type f -iname "*${pattern}*" \
			\( -iname '*.gba' -o -iname '*.gb' -o -iname '*.gbc' -o -iname '*.zip' \) 2>/dev/null | sort | head -n 1
	done | head -n 1
}

# Where RetroArch keeps this ROM's save today, so the launcher uses the same one
save_dir_for() { # rom system
	local rom="$1" sys="$2"
	local base; base="$(basename "${rom%.*}")"
	if [ -f "/userdata/saves/$sys/$base.srm" ]; then
		echo "/userdata/saves/$sys"
	elif [ -f "$(dirname "$rom")/$base.srm" ]; then
		dirname "$rom"
	else
		echo "/userdata/saves/$sys"
	fi
}

write_launcher() { # file rom system
	local file="$1" rom="$2" sys="$3"
	local saves; saves="$(save_dir_for "$rom" "$sys")"
	cat > "$file" <<EOF
#!/bin/bash
$MARK
# Starts $(basename "$rom") with the mgba-midisync core (USB MIDI sync).
CORE="$CORE"
ROM="$rom"
SAVES="$saves"
APPEND="/tmp/mgba-midisync-$sys.cfg"
mkdir -p "\$SAVES" /userdata/system/logs
cat > "\$APPEND" <<CFG
savefile_directory = "\$SAVES"
savestate_directory = "\$SAVES"
savefiles_in_content_dir = "false"
savestates_in_content_dir = "false"
sort_savefiles_enable = "false"
sort_savefiles_by_content_enable = "false"
sort_savestates_enable = "false"
sort_savestates_by_content_enable = "false"
system_directory = "/userdata/bios"
CFG
exec retroarch -L "\$CORE" --config /userdata/system/configs/retroarch/retroarchcustom.cfg --appendconfig "\$APPEND" "\$ROM"
EOF
	chmod +x "$file"
	echo "  $file"
	echo "    ROM:   $rom"
	echo "    saves: $saves"
}

echo "== Core"
mkdir -p /userdata/cores
cp "$CORE_SRC" "$CORE"
echo "  $CORE"

# Earlier test builds replaced the stock core with a bind mount; undo that
if grep -q " $OLD_BIND " /proc/mounts 2>/dev/null; then
	umount "$OLD_BIND" && echo "  removed old bind mount over the stock core"
fi
if [ -f /userdata/system/custom.sh ] && grep -q "$OLD_BIND" /userdata/system/custom.sh; then
	cp /userdata/system/custom.sh /userdata/system/custom.sh.mgba-midisync.bak
	sed -i "\|mount -o bind .*$OLD_BIND|d" /userdata/system/custom.sh
	# drop the file if only our empty if-block is left
	if ! grep -vE '^\s*(#.*|if \[ "\$1" = "start" \]; then|fi)?\s*$' /userdata/system/custom.sh | grep -q .; then
		rm /userdata/system/custom.sh
		echo "  removed custom.sh (it only held the old bind mount; backup: custom.sh.mgba-midisync.bak)"
	else
		echo "  removed the old bind mount line from custom.sh (backup: custom.sh.mgba-midisync.bak)"
	fi
fi

echo "== Ports launchers"
mkdir -p "$PORTS"
[ -n "$FMS_ROM" ] || FMS_ROM="$(find_rom fms /userdata/roms/gba)"
[ -n "$LSDJ_ROM" ] || LSDJ_ROM="$(find_rom lsdj /userdata/roms/gb /userdata/roms/gbc)"
if [ -n "$FMS_ROM" ]; then
	write_launcher "$PORTS/FMS (MIDI Sync).sh" "$FMS_ROM" gba
else
	echo "  FMS ROM not found in /userdata/roms/gba (use --fms PATH)"
fi
if [ -n "$LSDJ_ROM" ]; then
	case "$LSDJ_ROM" in *.gbc|*/gbc/*) sys=gbc ;; *) sys=gb ;; esac
	write_launcher "$PORTS/LSDj (MIDI Sync).sh" "$LSDJ_ROM" "$sys"
else
	echo "  LSDj ROM not found in /userdata/roms/gb or /userdata/roms/gbc (use --lsdj PATH)"
fi

# Ask EmulationStation to rescan (ignore if its web API is off)
if command -v curl >/dev/null 2>&1; then
	curl -s -m 3 http://127.0.0.1:1234/reloadgames >/dev/null 2>&1 && echo "== Game lists reloaded" || true
fi

cat <<'EOF'
== Done
Start FMS or LSDj from Ports. The GBA / Game Boy lists still use the stock core.
In the game: RetroArch Quick Menu > Core Options > MIDI Sync (FMS / LSDj).
Log: /userdata/system/logs/mgba-midisync.log
If the entries don't show up in Ports: Start > Game settings > Update gamelists.
EOF
