#!/bin/bash
# Removes what mgba-midisync install.sh added. Saves are not touched.
MARK="# Generated by mgba-midisync install.sh"
CORE="/userdata/cores/mgba_midisync_libretro.so"

for f in /userdata/roms/ports/*.sh; do
	[ -f "$f" ] || continue
	if grep -qF "$MARK" "$f"; then
		rm -f "$f" && echo "removed $f"
	fi
done
if [ -f "$CORE" ]; then
	rm -f "$CORE" && echo "removed $CORE"
fi
rm -f /tmp/mgba-midisync-*.cfg
if command -v curl >/dev/null 2>&1; then
	curl -s -m 3 http://127.0.0.1:1234/reloadgames >/dev/null 2>&1 || true
fi
echo "Done. Optional leftovers: /userdata/system/configs/mgba-midisync.cfg, /userdata/system/logs/mgba-midisync.log"
